---
name: Add missing template files

on:
  workflow_dispatch: true
  push:
    branches: [main, master]

jobs:
  add-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure README.md exists
        run: |
          if [ ! -f ${{ github.workspace }}/README.md ]; then
            echo "# \$(basename \$GITHUB_REPOSITORY)" > \
              ${{ github.workspace }}/README.md
            echo "Created by GitHub Action on \$(date)" >> \
              ${{ github.workspace }}/README.md
          fi

      - name: Ensure LICENSE exists
        run: |
          if [ ! -f ${{ github.workspace }}/LICENSE ]; then
            echo "MIT License" > ${{ github.workspace }}/LICENSE
            echo "" >> ${{ github.workspace }}/LICENSE
            echo "(C) \$(date +'%Y') \$GITHUB_ACTOR" >> \
              ${{ github.workspace }}/LICENSE
          fi

      - name: Ensure .gitignore exists
        run: |
          if [ ! -f ${{ github.workspace }}/.gitignore ]; then
            echo "Data/" > ${{ github.workspace }}/.gitignore
            echo ".DS_Store" >> ${{ github.workspace }}/.gitignore
            echo "*.backup" >> ${{ github.workspace }}/.gitignore
          fi

      - name: Ensure CHANGELOG.md exists
        run: |
          if [ ! -f ${{ github.workspace }}/CHANGELOG.md ]; then
            echo "# Changelog" > ${{ github.workspace }}/CHANGELOG.md
            echo "All notable changes will be documented here." >> \
              ${{ github.workspace }}/CHANGELOG.md
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add missing template/support files"
          branch: ${{ github.ref_name }}
